version: 2
updates:
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/bench"
      - "/docs"
      - "/examples"
      - "/test"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
